// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxv5QnZJFRwgdN7LenEQzoDQG3Wty9Xk8',
    appId: '1:293290417830:web:52a4d858c4d8959a825e67',
    messagingSenderId: '293290417830',
    projectId: 'flutter-firebase-90b84',
    authDomain: 'flutter-firebase-90b84.firebaseapp.com',
    storageBucket: 'flutter-firebase-90b84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy72UlCr1z3YDXUIEETG78Cav_AwhNV6A',
    appId: '1:293290417830:android:58bc8facf190b682825e67',
    messagingSenderId: '293290417830',
    projectId: 'flutter-firebase-90b84',
    storageBucket: 'flutter-firebase-90b84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8hzvqYd8BVmjqVqHZg6D2dSbbGhaGl3c',
    appId: '1:293290417830:ios:9840e54791bc3b0a825e67',
    messagingSenderId: '293290417830',
    projectId: 'flutter-firebase-90b84',
    storageBucket: 'flutter-firebase-90b84.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8hzvqYd8BVmjqVqHZg6D2dSbbGhaGl3c',
    appId: '1:293290417830:ios:67cfd1118d8a2f14825e67',
    messagingSenderId: '293290417830',
    projectId: 'flutter-firebase-90b84',
    storageBucket: 'flutter-firebase-90b84.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
